"""'init'

Revision ID: 7bfe1d451c94
Revises: 
Create Date: 2020-10-07 23:33:51.625421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bfe1d451c94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('director', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('genre', sa.String(length=50), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('castmovie',
    sa.Column('castid', sa.Integer(), nullable=True),
    sa.Column('movieid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['castid'], ['cast.id'], ),
    sa.ForeignKeyConstraint(['movieid'], ['movie.id'], )
    )
    op.create_table('favoritemovieuser',
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('movieid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movieid'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], )
    )
    op.create_table('recommendmovieuser',
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('movieid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movieid'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], )
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.String(length=1000), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('movie', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchedmovieuser',
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('movieid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movieid'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], )
    )
    op.create_table('wishlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wishlistmovie',
    sa.Column('wishlistid', sa.Integer(), nullable=True),
    sa.Column('movieid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movieid'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['wishlistid'], ['wishlist.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishlistmovie')
    op.drop_table('wishlist')
    op.drop_table('watchedmovieuser')
    op.drop_table('reviews')
    op.drop_table('recommendmovieuser')
    op.drop_table('favoritemovieuser')
    op.drop_table('castmovie')
    op.drop_table('user')
    op.drop_table('movie')
    op.drop_table('cast')
    # ### end Alembic commands ###
