"""'update'

Revision ID: ca013aac2619
Revises: 7bfe1d451c94
Create Date: 2020-11-04 12:08:37.603341

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ca013aac2619'
down_revision = '7bfe1d451c94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cast')
    op.drop_table('castmovie')
    op.add_column('movie', sa.Column('actors', sa.String(length=500), nullable=True))
    op.add_column('movie', sa.Column('external_rating', sa.Float(), nullable=True))
    op.add_column('movie', sa.Column('imdb_id', sa.String(length=10), nullable=True))
    op.add_column('movie', sa.Column('original_language', sa.String(length=50), nullable=True))
    op.add_column('movie', sa.Column('original_title', sa.String(length=200), nullable=True))
    op.add_column('movie', sa.Column('popularity', sa.Float(), nullable=True))
    op.add_column('movie', sa.Column('poster_path', sa.String(length=200), nullable=True))
    op.add_column('movie', sa.Column('tmdb_id', sa.String(length=15), nullable=True))
    op.drop_column('movie', 'language')
    op.drop_column('movie', 'name')
    op.add_column('user', sa.Column('image_url', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'image_url')
    op.add_column('movie', sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=50), nullable=True))
    op.add_column('movie', sa.Column('language', mysql.VARCHAR(collation='utf8_unicode_ci', length=50), nullable=True))
    op.drop_column('movie', 'tmdb_id')
    op.drop_column('movie', 'poster_path')
    op.drop_column('movie', 'popularity')
    op.drop_column('movie', 'original_title')
    op.drop_column('movie', 'original_language')
    op.drop_column('movie', 'imdb_id')
    op.drop_column('movie', 'external_rating')
    op.drop_column('movie', 'actors')
    op.create_table('castmovie',
    sa.Column('castid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('movieid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['castid'], ['cast.id'], name='castmovie_ibfk_1'),
    sa.ForeignKeyConstraint(['movieid'], ['movie.id'], name='castmovie_ibfk_2'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('cast',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
